"use client";
import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'hi' | 'ta';

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
    en: {
        // Nav
        'nav_home': 'Home',
        // Waste Types
        'rice_straw': 'Rice Straw',
        'wheat_stubble': 'Wheat Stubble',
        'sugarcane_trash': 'Sugarcane Trash',
        'sugarcane_bagasse': 'Sugarcane Bagasse',
        'corn_husk': 'Corn Husk',
        'mustard_stalk': 'Mustard Stalk',
        'soybean_residue': 'Soybean Residue',
        'cotton_stalk': 'Cotton Stalk',
        'miscellaneous': 'Miscellaneous',
        'nav_about': 'About',
        'nav_how_it_works': 'How it Works',
        'nav_login': 'Login',
        'nav_get_started': 'Get Started',
        'nav_marketplace': 'Marketplace',
        // Hero
        'hero_title': 'Turn Farm Waste into Wealth',
        'hero_subtitle': 'The global sustainable marketplace connecting farmers to industries. Eliminate stubble burning while earning more.',
        'hero_cta_primary': 'Join as Farmer',
        'hero_cta_secondary': 'Join as Buyer',
        'hero_badge': 'Live Biomass Marketplace',
        // Home Features
        'feat_instant_val': 'Instant Valuation',
        'feat_instant_val_desc': 'Our AI analyzes your crop waste and gives you a fair market price instantly.',
        'feat_zero_burning': 'Zero Burning',
        'feat_zero_burning_desc': 'Save the soil and the air. Every ton sold is a ton not removed by fire.',
        'feat_industry_ready': 'Industry Ready',
        'feat_industry_ready_desc': 'Direct connection to bio-energy plants and paper mills needing your raw material.',
        'feat_price_pred': 'AI Price Prediction',
        'feat_price_pred_desc': 'Get accurate market forecasts to decide the best time to sell your harvest waste.',
        'feat_smart_class': 'Smart Classification',
        'feat_smart_class_desc': 'Snap a photo. Our AI instantly calls out the waste type, quality, and estimated value.',
        'feat_voice_ast': 'Voice Assistant',
        'feat_voice_ast_desc': 'Navigate effortlessly. Just speak to list your produce or check prices in your language.',
        // About Page
        'about_title': 'Ending the Era of Stubble Burning',
        'about_subtitle': 'StubbleX is a technology-driven marketplace dedicated to turning agricultural waste ("Parali") from a pollution hazard into a valuable economic resource.',
        'about_mission': 'Our Mission',
        'about_stubble_burning': 'Stubble Burning',
        'about_for_farmers': 'For Farmers',
        'about_for_farmers_desc': 'We provide farmers with a direct platform to sell crop residue instantly, verifying quality with AI and ensuring fair payments.',
        'about_for_industry': 'For Industry',
        'about_for_industry_desc': 'We secure a reliable supply chain of biomass for biofuel plants, paper mills, and packaging industries, reducing their carbon footprint.',
        'about_for_planet': 'For Planet',
        'about_for_planet_desc': 'By monetizing waste, we eliminate the need for burning, drastically reducing smog and particulate matter in Northern India.',
        // Impact Section
        'impact_label': 'Real Impact',
        'impact_title': 'From Waste to Worth',
        'impact_desc': 'See how stubble is transformed into valuable eco-friendly products, creating a circular economy that benefits everyone.',
        // Footer
        'footer_desc': 'Turning agricultural waste into economic worth. Join the revolution for a cleaner, wealthier India.',
        'footer_what_we_do': 'What We Do',
        'footer_contact': 'Contact Us',
        'footer_rights': 'All rights reserved.',
        // Testimonials
        'testi_label': 'Real Income',
        'testi_title_part1': 'Harvesting',
        'testi_title_part2': 'Wealth',
        'testi_title_part3': 'From Waste.',
        'testi_subtitle': 'Join over 5,000+ farmers turning a storage headache into a steady new income stream.',
        'testi_earnings': 'Season Earnings',
        // Leaderboard
        'lead_weekly': 'Weekly Rankings',
        'lead_title_part1': 'Green Impact',
        'lead_title_part2': 'Leaderboard',
        'lead_subtitle': 'Top performing farmers leading the sustainability revolution.',
        'lead_rank_note': 'Rankings are based on your Green Score impact.',
        'lead_points': 'Points',
        'lead_rank': 'Rank',
        'lead_farmer': 'Farmer',
        'lead_impact_score': 'Impact Score',
        'lead_co2_saved': 'CO2 Saved',
        'lead_you': 'You',
        'lead_your_stats': 'Your Stats',
        'lead_current_rank': 'Current Rank',
        'lead_recycled': 'Recycled',
        'lead_total_points': 'Total Points',
        // Buyer Dashboard
        'buyer_dash_title': 'Procurement Dashboard',
        'buyer_dash_subtitle': 'Overview of your biomass sourcing and environmental impact.',
        'buyer_stat_offset': 'Carbon Offset',
        'buyer_stat_biomass': 'Biomass Secured',
        'buyer_stat_spend': 'Total Spend',
        'buyer_stat_target': 'Target',
        'buyer_stat_avg_cost': 'Avg cost',
        'buyer_marketplace': 'Live Marketplace',
        'buyer_filters': 'Filters',
        'buyer_search_placeholder': 'Search by crop, location, or quantity...',
        'buyer_quantity': 'Quantity',
        'buyer_price_ask': 'Price Ask',
        'buyer_distance': 'Distance',
        'buyer_request_pickup': 'Request Pickup',
        // Testimonials Quotes
        'testi_quote_rajesh': 'I used to pay fines for burning stubble. Now, StubbleX pays me for it. Last season, I cleared my debt just by selling waste I used to burn.',
        'testi_quote_sunita': "The pickup was arranged within 24 hours. The money was credited to my bank account instantly. It's safe, legal, and profitable.",
        'testi_quote_vikram': 'We aggregated stubble from 20 small farmers. Selling in bulk to the bio-energy plant via StubbleX gave us the best market rate.',
        'testi_quote_amandeep': "Previously, managing waste was a headache. Now it's a revenue stream. The app is so easy to use even for my father.",
        'testi_quote_meera': 'StubbleX connected me directly to paper mills. Better prices, no middlemen, and I feel good about helping the environment.',
        // AI Classification Details
        'ai_upload_title': 'Upload Waste Image',
        'ai_upload_desc': 'Drag and drop your image here, or click to browse',
        'ai_upload_supports': 'Supports JPG, PNG, WebP (max 10MB)',
        'ai_browse_files': 'Browse Files',
        'ai_take_photo': 'Take Photo',
        'ai_classify_complete': 'Classification Complete',
        'ai_confidence_score': 'Confidence Score',
        'ai_est_market_value': 'Estimated Market Value',
        'ai_impact_title': 'Environmental Impact',
        'ai_co2_reduction': 'CO2 Reduction',
        'ai_nitrogen_retained': 'Nitrogen Retained',
        'ai_water_savings': 'Water Savings',
        'ai_industrial_reuse': 'Industrial Reuse Options',
        'ai_market_demand': 'Market Demand',
        'ai_application': 'Application',
        'ai_processing': 'Processing Required',
        'ai_classify_another': 'Classify Another Image',
        'ai_per_ton': 'per ton',
        'ai_vs_burning': 'per ton vs burning',
        'ai_nutrients_saved': 'soil nutrients saved',
        'ai_water_conserved': 'water conserved',
        'ai_identified_with': 'Identified with',
        'ai_confidence': 'confidence',
        'voice_listening': 'Listening for (Crop Type) and (Quantity)...',
        'voice_recognized': 'Recognized',
        'dash_welcome': 'Welcome Back',
        'voice_error': 'Error recognizing speech.',
        // Dashboard Recent Orders
        'dash_recent_orders': 'Recent Orders',
        'dash_order_id': 'Order ID',
        'dash_date': 'Date',
        'dash_item': 'Item',
        'dash_qty': 'Qty',
        'dash_amount': 'Amount',
        'dash_status': 'Status',
        'dash_status_paid': 'Paid',
        'dash_status_picked': 'Picked Up',
        'dash_track_earnings': 'Track your earnings and list new harvest waste.',
        // Create Listing
        'dash_create_listing': 'Create New Listing',
        'dash_waste_type': 'Waste Type',
        'dash_qty_tons': 'Quantity (Tons)',
        'dash_farm_loc': 'Farm Location',
        'dash_pincode_placeholder': 'Enter Pincode',
        'dash_upload_photo': 'Upload Photo & AI Classify',
        'dash_click_upload': 'Click to upload photo',
        'dash_ai_classify_btn': 'AI Classify Waste',
        'dash_map_title': 'Village Impact Map',
        'dash_map_desc': 'Real-time satellite detection of burning hotspots.',
        'dash_cert_btn': 'Download AI Carbon Certificate',
        'kyc_ocr_scanning': 'Scanning document...',
        'kyc_ocr_success': 'ID read successfully!',
        'dash_classifying': 'Classifying...',
        'dash_ai_complete': 'AI Classification Complete!',
        'dash_detected': 'Detected',
        'dash_confidence': 'Confidence',
        'dash_price_prediction': 'AI Price Prediction',
        'dash_analyzing': 'Analyzing market...',
        'dash_estimated_value': 'Estimated Market Value based on AI analysis.',
        // My Listings
        'list_title': 'My Listings',
        'list_new_btn': '+ New Listing',
        'list_on': 'Listed on',
        'list_status_active': 'Active',
        'list_status_sold': 'Sold',
        // AI Classify Page
        'ai_back_dash': 'Back to Dashboard',
        'ai_title': 'AI Waste Classification',
        'ai_desc': 'Upload a photo of agricultural waste to identify its type and discover reuse opportunities',
        'ai_how_works': 'How it works:',
        'ai_how_desc': 'Our AI model uses advanced image recognition to classify agricultural waste into categories like rice straw, wheat stubble, sugarcane bagasse, and more. You\'ll receive instant insights on market value and industrial reuse options.',
        'ai_tips_title': 'Tips for Best Results',
        'ai_tip_1_title': 'Good Lighting',
        'ai_tip_1_desc': 'Take photos in bright, natural light',
        'ai_tip_2_title': 'Clear Focus',
        'ai_tip_2_desc': 'Ensure the waste is in focus and visible',
        'ai_tip_3_title': 'Close-up Shot',
        'ai_tip_3_desc': 'Get close to show texture and details',
        'ai_analyzing_img': 'Analyzing image...',
        'ai_identifying': 'Our AI is identifying the waste type',
        // KYC
        'kyc_title': 'Complete Your KYC',
        'kyc_desc': 'To start selling on StubbleX, we need to verify your identity. This helps keep our community safe.',
        'kyc_requirement': 'You\'ll need your Aadhar Card or PAN Card for verification.',
        'kyc_start_btn': 'Start Verification',
        'kyc_verify_id': 'Verify Identity',
        'kyc_upload_id_desc': 'Upload a photo of your ID Proof',
        'kyc_doc_type': 'Document Type',
        'kyc_tap_capture': 'Tap to Capture or Upload',
        'kyc_front_side': 'Front side of the document',
        'kyc_id_number': 'ID Number',
        'kyc_enter_id': 'Enter ID number',
        'kyc_submit_btn': 'Submit for Verification',
        'kyc_verifying': 'Verifying...',
        'kyc_success_title': 'Verification Successful!',
        'kyc_success_desc': 'Your KYC is complete. You can now list your products on the global marketplace.',
        'kyc_go_dash': 'Go to Dashboard',
        // Dashboard Nav
        'dash_nav_overview': 'Overview',
        'dash_nav_map': 'Impact Map',
        'dash_nav_listings': 'My Listings',
        'dash_nav_classify': 'AI Waste Classification',
        'dash_nav_leaderboard': 'Leaderboard',
        'dash_nav_profile': 'Profile',
        'dash_nav_orders': 'Orders',
        'dash_nav_company': 'Company Profile',
        'dash_nav_settings': 'Settings',
        'dash_nav_signout': 'Sign Out',
        // How it Works Page
        'how_title': 'How StubbleX Works',
        'how_farmer_step1': 'Upload Listing',
        'how_farmer_step1_desc': 'Take a photo of your stubble. Our AI automatically identifies the type (Rice/Wheat) and estimates quality.',
        'how_farmer_step2': 'Get Instant Price',
        'how_farmer_step2_desc': 'Receive a fair market price globally calculated based on demand, quantity, and moisture content.',
        'how_farmer_step3': 'Schedule Pickup',
        'how_farmer_step3_desc': 'Confirm the sale. A partner logistics truck arrives at your farm to collect the waste. You get paid instantly.',
        'how_buyer_step1': 'Browse Marketplace',
        'how_buyer_step1_desc': 'Filter available biomass by type, location, volume, and moisture content. View real images.',
        'how_buyer_step2': 'Secure Supply',
        'how_buyer_step2_desc': 'Place bulk orders. We aggregate small farm holdings into large, industry-ready shipments.',
        'how_buyer_step3': 'Track Impact',
        'how_buyer_step3_desc': 'Monitor your carbon offset and secured biomass stats directly from your corporate dashboard.',
        // Dashboard
        'dash_title': 'Farmer Dashboard',
        'dash_earnings': 'Total Earnings',
        'dash_waste_sold': 'Waste Sold',
        'dash_orders': 'Orders Completed',
        'dash_new_listing': 'New Listing',
        'list_now': 'List for Sale',
        'use_voice': 'Use Voice',
        'leaderboard': 'Leaderboard',
        'profile': 'Profile',
        'sign_out': 'Sign Out',
        'kyc_needed': 'Complete KYC'
    },
    hi: {
        // Nav
        'nav_home': 'होम',
        // Waste Types
        'rice_straw': 'धान की पराली',
        'wheat_stubble': 'गेहूं की पराली',
        'sugarcane_trash': 'गन्ने का कचरा',
        'sugarcane_bagasse': 'गन्ने की खोई',
        'corn_husk': 'मक्के का छिलका',
        'mustard_stalk': 'सरसों की डंठल',
        'soybean_residue': 'सोयाबीन का अवशेष',
        'cotton_stalk': 'कपास की डंठल',
        'miscellaneous': 'विविध',
        'nav_about': 'हमारे बारे में',
        'nav_how_it_works': 'यह कैसे काम करता है',
        'nav_login': 'लॉगिन',
        'nav_get_started': 'शुरू करें',
        'nav_marketplace': 'मार्केटप्लेस',
        // Hero
        'hero_title': 'खेती के कचरे को धन में बदलें',
        'hero_subtitle': 'किसानों को उद्योगों से जोड़ने वाला वैश्विक टिकाऊ बाज़ार। अधिक कमाई करते हुए पराली जलाने की समस्या को समाप्त करें।',
        'hero_cta_primary': 'किसान के रूप में जुड़ें',
        'hero_cta_secondary': 'खरीदार के रूप में जुड़ें',
        'hero_badge': 'लाइव बायोमास मार्केटप्लेस',
        // Home Features
        'feat_instant_val': 'तत्काल मूल्यांकन',
        'feat_instant_val_desc': 'हमारा एआई आपके फसल कचरे का विश्लेषण करता है और आपको तुरंत उचित बाजार मूल्य देता है।',
        'feat_zero_burning': 'शून्य दहन',
        'feat_zero_burning_desc': 'मिट्टी और हवा को बचाएं। बेचा गया हर टन एक टन है जिसे आग से नहीं हटाया गया।',
        'feat_industry_ready': 'उद्योग के लिए तैयार',
        'feat_industry_ready_desc': 'बायो-एनर्जी प्लांट और पेपर मिलों से सीधा संबंध जिन्हें आपके कच्चे माल की आवश्यकता है।',
        'feat_price_pred': 'एआई मूल्य भविष्यवाणी',
        'feat_price_pred_desc': 'अपने फसल कचरे को बेचने का सबसे अच्छा समय तय करने के लिए सटीक बाजार पूर्वानुमान प्राप्त करें।',
        'feat_smart_class': 'स्मार्ट वर्गीकरण',
        'feat_smart_class_desc': 'एक फोटो खींचें। हमारा एआई तुरंत कचरे के प्रकार, गुणवत्ता और अनुमानित मूल्य की पहचान करता है।',
        'feat_voice_ast': 'वॉयस असिस्टेंट',
        'feat_voice_ast_desc': 'नाखूनों के माध्यम से नेविगेट करें। बस अपनी उपज को सूचीबद्ध करने या अपनी भाषा में कीमतों की जांच करने के लिए बोलें।',
        // About Page
        'about_title': 'पराली जलाने के युग का अंत',
        'about_subtitle': 'StubbleX एक तकनीक-आधारित बाज़ार है जो कृषि कचरे ("पराली") को प्रदूषण के खतरे से एक मूल्यवान आर्थिक संसाधन में बदलने के लिए समर्पित है।',
        'about_mission': 'हमारा मिशन',
        'about_stubble_burning': 'पराली जलाना',
        'about_for_farmers': 'किसानों के लिए',
        'about_for_farmers_desc': 'हम किसानों को फसल अवशेषों को तुरंत बेचने के लिए एक सीधा मंच प्रदान करते हैं, एआई के साथ गुणवत्ता की पुष्टि करते हैं और उचित भुगतान सुनिश्चित करते हैं।',
        'about_for_industry': 'उद्योग के लिए',
        'about_for_industry_desc': 'हम जैव ईंधन संयंत्रों, पेपर मिलों और पैकेजिंग उद्योगों के लिए बायोमास की एक विश्वसनीय आपूर्ति श्रृंखला सुरक्षित करते हैं।',
        'about_for_planet': 'ग्रह के लिए',
        'about_for_planet_desc': 'कचरे का मुद्रीकरण करके, हम जलाने की आवश्यकता को समाप्त करते हैं, जिससे उत्तर भारत में धुंध और पार्टिकुलेट मैटर बहुत कम हो जाता है।',
        // Impact Section
        'impact_label': 'वास्तविक प्रभाव',
        'impact_title': 'कचरे से मूल्य तक',
        'impact_desc': 'देखें कि कैसे पराली को मूल्यवान पर्यावरण के अनुकूल उत्पादों में बदल दिया जाता है, जिससे एक चक्रीय अर्थव्यवस्था बनती है जो सभी को लाभान्वित करती है।',
        // Footer
        'footer_desc': 'कृषि अपशिष्ट को आर्थिक मूल्य में बदलना। स्वच्छ, समृद्ध भारत की क्रांति में शामिल हों।',
        'footer_what_we_do': 'हम क्या करते हैं',
        'footer_contact': 'संपर्क करें',
        'footer_rights': 'सर्वाधिकार सुरक्षित।',
        // Testimonials
        'testi_label': 'वास्तविक आय',
        'testi_title_part1': 'कचरे से',
        'testi_title_part2': 'धन',
        'testi_title_part3': 'की कटाई।',
        'testi_subtitle': 'भंडारण के सिरदर्द को एक स्थिर नए आय स्रोत में बदलने वाले 5,000+ से अधिक किसानों में शामिल हों।',
        'testi_earnings': 'सीजन की कमाई',
        // Leaderboard
        'lead_weekly': 'साप्ताहिक रैंकिंग',
        'lead_title_part1': 'हरित प्रभाव',
        'lead_title_part2': 'लीडरबोर्ड',
        'lead_subtitle': 'स्थिरता क्रांति का नेतृत्व करने वाले शीर्ष प्रदर्शन करने वाले किसान।',
        'lead_rank_note': 'रैंकिंग आपके ग्रीन स्कोर प्रभाव पर आधारित है।',
        'lead_points': 'अंक',
        'lead_rank': 'रैंक',
        'lead_farmer': 'किसान',
        'lead_impact_score': 'प्रभाव स्कोर',
        'lead_co2_saved': 'CO2 बचाया',
        'lead_you': 'आप',
        'lead_your_stats': 'आपके आंकड़े',
        'lead_current_rank': 'वर्तमान रैंक',
        'lead_recycled': 'पुनर्नवीनीकरण',
        'lead_total_points': 'कुल अंक',
        // Buyer Dashboard
        'buyer_dash_title': 'खरीद डैशबोर्ड',
        'buyer_dash_subtitle': 'आपके बायोमास सोर्सिंग और पर्यावरणीय प्रभाव का अवलोकन।',
        'buyer_stat_offset': 'कार्बन ऑफसेट',
        'buyer_stat_biomass': 'बायोमास सुरक्षित',
        'buyer_stat_spend': 'कुल खर्च',
        'buyer_stat_target': 'लक्ष्य',
        'buyer_stat_avg_cost': 'औसत लागत',
        'buyer_marketplace': 'लाइव मार्केटप्लेस',
        'buyer_filters': 'फ़िल्टर',
        'buyer_search_placeholder': 'फसल, स्थान या मात्रा के आधार पर खोजें...',
        'buyer_quantity': 'मात्रा',
        'buyer_price_ask': 'कीमत मांग',
        'buyer_distance': 'दूरी',
        'buyer_request_pickup': 'पिकअप का अनुरोध करें',
        // Testimonials Quotes
        'testi_quote_rajesh': 'मैं पराली जलाने के लिए जुर्माना भरता था। अब, StubbleX मुझे इसके लिए भुगतान करता है। पिछले सीजन में, मैंने सिर्फ उस कचरे को बेचकर अपना कर्ज चुका दिया जिसे मैं जला देता था।',
        'testi_quote_sunita': "पिकअप 24 घंटे के भीतर व्यवस्थित किया गया था। पैसा तुरंत मेरे बैंक खाते में जमा कर दिया गया। यह सुरक्षित, कानूनी और लाभदायक है।",
        'testi_quote_vikram': 'हमने 20 छोटे किसानों से पराली इकट्ठा की। StubbleX के माध्यम से बायो-एनर्जी प्लांट को थोक में बेचने से हमें सबसे अच्छी बाजार दर मिली।',
        'testi_quote_amandeep': "पहले, कचरे का प्रबंधन करना एक सिरदर्द था। अब यह एक आय का स्रोत है। ऐप का उपयोग करना इतना आसान है कि मेरे पिता भी इसका उपयोग कर सकते हैं।",
        'testi_quote_meera': 'StubbleX ने मुझे सीधे पेपर मिलों से जोड़ा। बेहतर कीमतें, कोई बिचौलिया नहीं, और मुझे पर्यावरण की मदद करने में अच्छा लगता है।',
        // AI Classification Details
        'ai_upload_title': 'अपशिष्ट छवि अपलोड करें',
        'ai_upload_desc': 'अपनी छवि यहाँ खींचें और छोड़ें, या ब्राउज़ करने के लिए क्लिक करें',
        'ai_upload_supports': 'JPG, PNG, WebP का समर्थन करता है (अधिकतम 10MB)',
        'ai_browse_files': 'फ़ाइलें ब्राउज़ करें',
        'ai_take_photo': 'फोटो लें',
        'ai_classify_complete': 'वर्गीकरण पूर्ण',
        'ai_confidence_score': 'आत्मविश्वास स्कोर',
        'ai_est_market_value': 'अनुमानित बाजार मूल्य',
        'ai_impact_title': 'पर्यावरणीय प्रभाव',
        'ai_co2_reduction': 'CO2 कमी',
        'ai_nitrogen_retained': 'नाइट्रोजन बरकरार',
        'ai_water_savings': 'पानी की बचत',
        'ai_industrial_reuse': 'औद्योगिक पुन: उपयोग के विकल्प',
        'ai_market_demand': 'बाजार की मांग',
        'ai_application': 'अनुप्रयोग',
        'ai_processing': 'प्रसंस्करण आवश्यक',
        'ai_classify_another': 'दूसरी छवि वर्गीकृत करें',
        'ai_per_ton': 'प्रति टन',
        'ai_vs_burning': 'प्रति टन बनाम जलन',
        'ai_nutrients_saved': 'मिट्टी के पोषक तत्व बचाए गए',
        'ai_water_conserved': 'पानी संरक्षित',
        'ai_identified_with': 'इसके साथ पहचाना गया',
        'ai_confidence': 'आत्मविश्वास',
        'voice_listening': '(फसल का प्रकार) और (मात्रा) के लिए सुन रहा हूँ...',
        'voice_recognized': 'पहचाना गया',
        'dash_welcome': 'सुस्वागतम',
        'voice_error': 'आवाज पहचानने में त्रुटि।',
        // Dashboard Recent Orders
        'dash_recent_orders': 'हाल के ऑर्डर',
        'dash_order_id': 'ऑर्डर आईडी',
        'dash_date': 'तारीख',
        'dash_item': 'आइटम',
        'dash_qty': 'मात्रा',
        'dash_amount': 'राशि',
        'dash_status': 'स्थिति',
        'dash_status_paid': 'भुगतान किया गया',
        'dash_status_picked': 'उठाया गया',
        'dash_track_earnings': 'अपनी कमाई को ट्रैक करें और नए फसल कचरे को लिस्ट करें।',
        // Create Listing
        'dash_create_listing': 'नई लिस्टिंग बनाएं',
        'dash_waste_type': 'कचरे का प्रकार',
        'dash_qty_tons': 'मात्रा (टन)',
        'dash_farm_loc': 'फार्म का स्थान',
        'dash_pincode_placeholder': 'पिनकोड दर्ज करें',
        'dash_upload_photo': 'फोटो अपलोड करें और एआई वर्गीकरण करें',
        'dash_click_upload': 'फोटो अपलोड करने के लिए क्लिक करें',
        'dash_ai_classify_btn': 'एआई कचरा वर्गीकरण',
        'dash_map_title': 'गांव प्रभाव मानचित्र',
        'dash_map_desc': 'जलते हुए हॉटस्पॉट की रीयल-टाइम सैटेलाइट पहचान।',
        'dash_cert_btn': 'एआई कार्बन प्रमाणपत्र डाउनलोड करें',
        'kyc_ocr_scanning': 'दस्तावेज़ स्कैन किया जा रहा है...',
        'kyc_ocr_success': 'आईडी सफलतापूर्वक पढ़ी गई!',
        'dash_classifying': 'वर्गीकरण हो रहा है...',
        'dash_ai_complete': 'एआई वर्गीकरण पूरा हुआ!',
        'dash_detected': 'पहचाना गया',
        'dash_confidence': 'आत्मविश्वास',
        'dash_price_prediction': 'एआई मूल्य भविष्यवाणी',
        'dash_analyzing': 'बाजार का विश्लेषण हो रहा है...',
        'dash_estimated_value': 'एआई विश्लेषण के आधार पर अनुमानित बाजार मूल्य।',
        // My Listings
        'list_title': 'मेरी लिस्टिंग',
        'list_new_btn': '+ नई लिस्टिंग',
        'list_on': 'लिस्ट किया गया',
        'list_status_active': 'सक्रिय',
        'list_status_sold': 'बिका हुआ',
        // AI Classify Page
        'ai_back_dash': 'डैशबोर्ड पर वापस जाएं',
        'ai_title': 'एआई कचरा वर्गीकरण',
        'ai_desc': 'कृषि अपशिष्ट के प्रकार की पहचान करने और पुन: उपयोग के अवसरों की खोज करने के लिए उसकी एक फोटो अपलोड करें',
        'ai_how_works': 'यह कैसे काम करता है:',
        'ai_how_desc': 'हमारा एआई मॉडल कृषि अपशिष्ट को चावल की पराली, गेहूं की पराली, गन्ने की खोई, और बहुत कुछ जैसी श्रेणियों में वर्गीकृत करने के लिए उन्नत छवि पहचान का उपयोग करता है। आपको बाजार मूल्य और औद्योगिक पुन: उपयोग विकल्पों पर तत्काल जानकारी प्राप्त होगी।',
        'ai_tips_title': 'सर्वोत्तम परिणामों के लिए सुझाव',
        'ai_tip_1_title': 'अच्छी रोशनी',
        'ai_tip_1_desc': 'तेज, प्राकृतिक रोशनी में फोटो लें',
        'ai_tip_2_title': 'स्पष्ट फोकस',
        'ai_tip_2_desc': 'सुनिश्चित करें कि कचरा फोकस में है और दिखाई दे रहा है',
        'ai_tip_3_title': 'करीब से शॉट',
        'ai_tip_3_desc': 'बनावट और विवरण दिखाने के लिए करीब आएं',
        'ai_analyzing_img': 'छवि का विश्लेषण हो रहा है...',
        'ai_identifying': 'हमारा एआई कचरे के प्रकार की पहचान कर रहा है',
        // KYC
        'kyc_title': 'अपना केवाईसी पूरा करें',
        'kyc_desc': 'StubbleX पर बिक्री शुरू करने के लिए, हमें आपकी पहचान सत्यापित करने की आवश्यकता है। यह हमारे समुदाय को सुरक्षित रखने में मदद करता है।',
        'kyc_requirement': 'सत्यापन के लिए आपको अपने आधार कार्ड या पैन कार्ड की आवश्यकता होगी।',
        'kyc_start_btn': 'सत्यापन शुरू करें',
        'kyc_verify_id': 'पहचान सत्यापित करें',
        'kyc_upload_id_desc': 'अपने आईडी प्रमाण की एक फोटो अपलोड करें',
        'kyc_doc_type': 'दस्तावेज़ का प्रकार',
        'kyc_tap_capture': 'कैप्चर या अपलोड करने के लिए टैप करें',
        'kyc_front_side': 'दस्तावेज़ का सामने का हिस्सा',
        'kyc_id_number': 'आईडी नंबर',
        'kyc_enter_id': 'आईडी नंबर दर्ज करें',
        'kyc_submit_btn': 'सत्यापन के लिए सबमिट करें',
        'kyc_verifying': 'सत्यापन हो रहा है...',
        'kyc_success_title': 'सत्यापन सफल!',
        'kyc_success_desc': 'आपका केवाईसी पूरा हो गया है। अब आप वैश्विक मार्केटप्लेस पर अपने उत्पादों को लिस्ट कर सकते हैं।',
        'kyc_go_dash': 'डैशबोर्ड पर जाएं',
        // Dashboard Nav
        'dash_nav_overview': 'अवलोकन',
        'dash_nav_map': 'प्रभाव मानचित्र',
        'dash_nav_listings': 'मेरी लिस्टिंग',
        'dash_nav_classify': 'एआई कचरा वर्गीकरण',
        'dash_nav_leaderboard': 'लीडरबोर्ड',
        'dash_nav_profile': 'प्रोफ़ाइल',
        'dash_nav_orders': 'ऑर्डर',
        'dash_nav_company': 'कंपनी प्रोफ़ाइल',
        'dash_nav_settings': 'सेटिंग्स',
        'dash_nav_signout': 'साइन आउट',
        // How it Works Page
        'how_title': 'StubbleX कैसे काम करता है',
        'how_farmer_step1': 'लिस्टिंग अपलोड करें',
        'how_farmer_step1_desc': 'अपनी पराली का फोटो लें। हमारा एआई स्वचालित रूप से प्रकार (चावल/गेहूं) की पहचान करता है और गुणवत्ता का अनुमान लगाता है।',
        'how_farmer_step2': 'तत्काल मूल्य प्राप्त करें',
        'how_farmer_step2_desc': 'मांग, मात्रा और नमी की मात्रा के आधार पर वैश्विक स्तर पर गणना की गई उचित बाजार कीमत प्राप्त करें।',
        'how_farmer_step3': 'पिकअप शेड्यूल करें',
        'how_farmer_step3_desc': 'बिक्री की पुष्टि करें। कचरा इकट्ठा करने के लिए एक पार्टनर लॉजिस्टिक्स ट्रक आपके फार्म पर पहुंचता है। आपको तुरंत भुगतान मिल जाता है।',
        'how_buyer_step1': 'मार्केटप्लेस ब्राउज़ करें',
        'how_buyer_step1_desc': 'प्रकार, स्थान, मात्रा और नमी की मात्रा के आधार पर उपलब्ध बायोमास को फ़िल्टर करें। वास्तविक छवियां देखें।',
        'how_buyer_step2': 'सुरक्षित आपूर्ति',
        'how_buyer_step2_desc': 'थोक ऑर्डर दें। हम छोटी कृषि जोतों को बड़े, उद्योग-तैयार शिपमेंट में एकत्रित करते हैं।',
        'how_buyer_step3': 'प्रभाव ट्रैक करें',
        'how_buyer_step3_desc': 'सीधे अपने कॉर्पोरेट डैशबोर्ड से अपने कार्बन ऑफसेट और सुरक्षित बायोमास आंकड़ों की निगरानी करें।',
        // Dashboard
        'dash_title': 'किसान डैशबोर्ड',
        'dash_earnings': 'कुल कमाई',
        'dash_waste_sold': 'बेचा गया कचरा',
        'dash_orders': 'पूरे किए गए ऑर्डर',
        'dash_new_listing': 'नई लिस्टिंग',
        'list_now': 'बिक्री के लिए लिस्ट करें',
        'use_voice': 'आवाज़ का उपयोग करें',
        'leaderboard': 'लीडरबोर्ड',
        'profile': 'प्रोफ़ाइल',
        'sign_out': 'साइन आउट',
        'kyc_needed': 'केवाईसी पूरा करें'
    },
    ta: {
        // Nav
        'nav_home': 'முகப்பு',
        // Waste Types
        'rice_straw': 'அரிசி வைக்கோல்',
        'wheat_stubble': 'கோதுமை வைக்கோல்',
        'sugarcane_trash': 'கரும்பு குப்பை',
        'sugarcane_bagasse': 'கரும்பு சக்கை',
        'corn_husk': 'சோள உமி',
        'mustard_stalk': 'கடுகுத் தண்டு',
        'soybean_residue': 'சோயாபீன் எஞ்சியவை',
        'cotton_stalk': 'பருத்தித் தண்டு',
        'miscellaneous': 'இதர',
        'nav_about': 'எங்களைப் பற்றி',
        'nav_how_it_works': 'இது எப்படி வேலை செய்கிறது',
        'nav_login': 'உள்நுழைய',
        'nav_get_started': 'தொடங்குங்கள்',
        'nav_marketplace': 'சந்தை',
        // Hero
        'hero_title': 'விவசாயக் கழிவுகளை செல்வமாக மாற்றவும்',
        'hero_subtitle': 'விவசாயிகளைத் தொழில்துறைகளுடன் இணைக்கும் உலகளாவிய நிலையான சந்தை. அதிக வருமானம் ஈட்டும் அதே வேளையில் வைக்கோல் எரிப்பைத் தவிர்க்கவும்.',
        'hero_cta_primary': 'விவசாயியாக சேரவும்',
        'hero_cta_secondary': 'வாங்குபவராக சேரவும்',
        // Home Features
        'feat_instant_val': 'உடனடி மதிப்பீடு',
        'feat_instant_val_desc': 'எங்கள் AI உங்கள் பயிர் கழிவுகளை பகுப்பாய்வு செய்து உங்களுக்கு உடனடி நியாயமான சந்தை விலையை வழங்குகிறது.',
        'feat_zero_burning': 'பூஜ்ஜிய எரிப்பு',
        'feat_zero_burning_desc': 'மண்ணையும் காற்றையும் காப்பாற்றுங்கள். விற்கப்படும் ஒவ்வொரு டன்னும் எரிக்கப்படாத ஒரு டன் ஆகும்.',
        'feat_industry_ready': 'தொழில்துறை தயார்',
        'feat_industry_ready_desc': 'உங்கள் மூலப்பொருள் தேவைப்படும் உயிர்-ஆற்றல் ஆலைகள் மற்றும் காகித ஆலைகளுடன் நேரடி தொடர்பு.',
        'feat_price_pred': 'AI விலை கணிப்பு',
        'feat_price_pred_desc': 'உங்கள் அறுவடை கழிவுகளை விற்க சிறந்த நேரத்தை தீர்மானிக்க துல்லியமான சந்தை முன்னறிவிப்புகளைப் பெறுங்கள்.',
        'feat_smart_class': 'ஸ்மார்ட் வகைப்பாடு',
        'feat_smart_class_desc': 'புகைப்படம் எடுங்கள். எங்கள் AI உடனடியாக கழிவு வகை, தரம் மற்றும் மதிப்பிடப்பட்ட மதிப்பை அழைக்கிறது.',
        'feat_voice_ast': 'குரல் உதவியாளர்',
        'feat_voice_ast_desc': 'சிரமமின்றி செல்லவும். உங்கள் விளைபொருட்களை பட்டியலிட அல்லது உங்கள் மொழியில் விலைகளை சரிபார்க்க பேசுங்கள்.',
        // About Page
        'about_title': 'வைக்கோல் எரிப்பு சகாப்தத்தை முடிவுக்குக் கொண்டுவருதல்',
        'about_subtitle': 'StubbleX என்பது விவசாயக் கழிவுகளை ("பராலி") ஒரு மாசு அபாயத்திலிருந்து ஒரு மதிப்புமிக்க பொருளாதார வளமாக மாற்றுவதற்காக அர்ப்பணிக்கப்பட்ட ஒரு தொழில்நுட்பம் சார்ந்த சந்தையாகும்.',
        'about_mission': 'எங்கள் நோக்கம்',
        'about_stubble_burning': 'வைக்கோல் எரிப்பு',
        'about_for_farmers': 'விவசாயிகளுக்கு',
        'about_for_farmers_desc': 'பயிர் எச்சங்களை உடனடியாக விற்க விவசாயிகளுக்கு நேரடி தளத்தை வழங்குகிறோம், AI மூலம் தரத்தை சரிபார்க்கிறோம் மற்றும் நியாயமான கட்டணங்களை உறுதி செய்கிறோம்.',
        'about_for_industry': 'தொழில்துறைக்கு',
        'about_for_industry_desc': 'உயிர் எரிபொருள் ஆலைகள், காகித ஆலைகள் மற்றும் பேக்கேஜிங் தொழில்களுக்கான உயிரினங்களின் நம்பகமான விநியோகச் சங்கிலியை நாங்கள் பாதுகாக்கிறோம்.',
        'about_for_planet': 'பூமிக்கு',
        'about_for_planet_desc': 'கழிவுகளைப் பணமாக்குவதன் மூலம், நாம் எரிக்க வேண்டிய அவசியத்தை நீக்குகிறோம், வட இந்தியாவில் புகை மற்றும் துகள்களை வெகுவாகக் குறைக்கிறோம்.',
        // Impact Section
        'impact_label': 'உண்மையான தாக்கம்',
        'impact_title': 'கழிவிலிருந்து மதிப்பு வரை',
        'impact_desc': 'வைக்கோல் எவ்வாறு மதிப்புமிக்க சூழல் நட்பு தயாரிப்புகளாக மாற்றப்படுகிறது என்பதைப் பாருங்கள், இது அனைவருக்கும் பயனளிக்கும் ஒரு வட்ட பொருளாதாரத்தை உருவாக்குகிறது.',
        // Footer
        'footer_desc': 'விவசாயக் கழிவுகளைப் பொருளாதார மதிப்பாக மாற்றுதல். தூய்மையான, வளமான இந்தியாவிற்கான புரட்சியில் சேருங்கள்.',
        'footer_what_we_do': 'நாங்கள் என்ன செய்கிறோம்',
        'footer_contact': 'எங்களைத் தொடர்பு கொள்ளுங்கள்',
        'footer_rights': 'அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை.',
        // Testimonials
        'testi_label': 'உண்மையான வருமானம்',
        'testi_title_part1': 'கழிவிலிருந்து',
        'testi_title_part2': 'செல்வத்தை',
        'testi_title_part3': 'அறுவடை செய்தல்.',
        'testi_subtitle': 'சேமிப்பு தலைவலியை ஒரு நிலையான புதிய வருமான நீரோடையாக மாற்றும் 5,000+ க்கும் மேற்பட்ட விவசாயிகளுடன் சேருங்கள்.',
        'testi_earnings': 'பருவக் கால வருவாய்',
        // Leaderboard
        'lead_weekly': 'வாராந்திர தரவரிசை',
        'lead_title_part1': 'பசுமை தாக்கம்',
        'lead_title_part2': 'தரவரிசைப் பட்டியல்',
        'lead_subtitle': 'நிலைத்தன்மை புரட்சியை முன்னெடுக்கும் சிறந்த விவசாயிகள்.',
        'lead_rank_note': 'தரவரிசைகள் உங்கள் பசுமை மதிப்பெண் தாக்கத்தை அடிப்படையாகக் கொண்டவை.',
        'lead_points': 'புள்ளிகள்',
        'lead_rank': 'தரம்',
        'lead_farmer': 'விவசாயி',
        'lead_impact_score': 'தாக்க மதிப்பெண்',
        'lead_co2_saved': 'CO2 சேமிக்கப்பட்டது',
        'lead_you': 'நீங்கள்',
        'lead_your_stats': 'உங்கள் புள்ளிவிவரங்கள்',
        'lead_current_rank': 'தற்போதைய தரம்',
        'lead_recycled': 'மறுசுழற்சி செய்யப்பட்டது',
        'lead_total_points': 'மொத்த புள்ளிகள்',
        // Buyer Dashboard
        'buyer_dash_title': 'கொள்முதல் டாஷ்போர்டு',
        'buyer_dash_subtitle': 'உங்கள் உயிரினங்களின் ஆதாரம் மற்றும் சுற்றுச்சூழல் தாக்கத்தின் மேலோட்டம்.',
        'buyer_stat_offset': 'கார்பன் ஆஃப்செட்',
        'buyer_stat_biomass': 'பாதுகாக்கப்பட்ட உயிரிப்பொருள்',
        'buyer_stat_spend': 'மொத்த செலவு',
        'buyer_stat_target': 'இலக்கு',
        'buyer_stat_avg_cost': 'சராசரி செலவு',
        'buyer_marketplace': 'நேரடி சந்தை',
        'buyer_filters': 'வடிகட்டிகள்',
        'buyer_search_placeholder': 'பயிர், இருப்பிடம் அல்லது அளவின் அடிப்படையில் தேடுங்கள்...',
        'buyer_quantity': 'அளவு',
        'buyer_price_ask': 'விலை கேட்பு',
        'buyer_distance': 'தூரம்',
        'buyer_request_pickup': 'பிக்கப்பைக் கோருங்கள்',
        // Testimonials Quotes
        'testi_quote_rajesh': 'வைக்கோல் எரித்ததற்காக நான் அபராதம் செலுத்தி வந்தேன். இப்போது, StubbleX அதற்காக எனக்கு பணம் கொடுக்கிறது. கடந்த பருவத்தில், நான் எரிக்கப் பயன்படுத்திய கழிவுகளை விற்பதன் மூலம் எனது கடனைத் தீர்த்தேன்.',
        'testi_quote_sunita': "பிக்கப் 24 மணி நேரத்திற்குள் ஏற்பாடு செய்யப்பட்டது. பணம் உடனடியாக எனது வங்கி கணக்கில் வரவு வைக்கப்பட்டது. இது பாதுகாப்பானது, சட்டபூர்வமானது மற்றும் லாபகரமானது.",
        'testi_quote_vikram': '20 சிறு விவசாயிகளிடமிருந்து வைக்கோலைச் சேகரித்தோம். StubbleX மூலம் உயிர்-ஆற்றல் ஆலைக்கு மொத்தமாக விற்பனை செய்தது எங்களுக்கு சிறந்த சந்தை விலையை அளித்தது.',
        'testi_quote_amandeep': "முன்பு, கழிவுகளை நிர்வகிப்பது ஒரு தலைவலியாக இருந்தது. இப்போது அது ஒரு வருமான நீரோடை. இந்த செயலியை எனது தந்தை கூட பயன்படுத்தும் வகையில் மிகவும் எளிமையாக உள்ளது.",
        'testi_quote_meera': 'StubbleX என்னை நேரடியாக காகித ஆலைகளுடன் இணைத்தது. சிறந்த விலைகள், இடைத்தரகர்கள் இல்லை, மேலும் சுற்றுச்சூழலுக்கு உதவுவதில் நான் மகிழ்ச்சியடைகிறேன்.',
        // AI Classification Details
        'ai_upload_title': 'கழிவுப் படத்தை பதிவேற்றவும்',
        'ai_upload_desc': 'உங்கள் படத்தை இங்கே இழுத்து விடவும் அல்லது உலாவ கிளிக் செய்யவும்',
        'ai_upload_supports': 'JPG, PNG, WebP ஐ ஆதரிக்கிறது (அதிகபட்சம் 10MB)',
        'ai_browse_files': 'கோப்புகளைத் தேடுங்கள்',
        'ai_take_photo': 'புகைப்படம் எடு',
        'ai_classify_complete': 'வகைப்படுத்தல் முடிந்தது',
        'ai_confidence_score': 'நம்பிக்கை மதிப்பெண்',
        'ai_est_market_value': 'மதிப்பிடப்பட்ட சந்தை மதிப்பு',
        'ai_impact_title': 'சுற்றுச்சூழல் தாக்கம்',
        'ai_co2_reduction': 'CO2 குறைப்பு',
        'ai_nitrogen_retained': 'தக்க வைக்கப்பட்ட நைட்ரஜன்',
        'ai_water_savings': 'நீர் சேமிப்பு',
        'ai_industrial_reuse': 'தொழில்துறை மறுபயன்பாட்டு விருப்பங்கள்',
        'ai_market_demand': 'சந்தை தேவை',
        'ai_application': 'பயன்பாடு',
        'ai_processing': 'செயலாக்கம் தேவை',
        'ai_classify_another': 'மற்றொரு படத்தை வகைப்படுத்தவும்',
        'ai_per_ton': 'ஒரு டன்னுக்கு',
        'ai_vs_burning': 'எரிப்பதற்கு எதிரான ஒரு டன்னுக்கு',
        'ai_nutrients_saved': 'மண் ஊட்டச்சத்துக்கள் சேமிக்கப்பட்டன',
        'ai_water_conserved': 'நீர் பாதுகாக்கப்பட்டது',
        'ai_identified_with': 'இதன் மூலம் அடையாளம் காணப்பட்டது',
        'ai_confidence': 'நம்பிக்கை',
        'voice_listening': '(பயிர் வகை) மற்றும் (அளவு) க்காகக் காத்திருக்கிறது...',
        'voice_recognized': 'அடையாளம் காணப்பட்டது',
        'dash_welcome': 'மீண்டும் வருக',
        'voice_error': 'பேச்சை அடையாளம் காண்பதில் பிழை.',
        // Dashboard Recent Orders
        'dash_recent_orders': 'சமீபத்திய ஆர்டர்கள்',
        'dash_order_id': 'ஆர்டர் ஐடி',
        'dash_date': 'தேதி',
        'dash_item': 'பொருள்',
        'dash_qty': 'அளவு',
        'dash_amount': 'தொகை',
        'dash_status': 'நிலை',
        'dash_status_paid': 'செலுத்தப்பட்டது',
        'dash_status_picked': 'எடுக்கப்பட்டது',
        'dash_track_earnings': 'உங்கள் வருவாயைக் கண்காணித்து புதிய அறுவடை கழிவுகளைப் பட்டியலிடுங்கள்.',
        // Create Listing
        'dash_create_listing': 'புதிய பட்டியலை உருவாக்கவும்',
        'dash_waste_type': 'கழிவு வகை',
        'dash_qty_tons': 'அளவு (டன்கள்)',
        'dash_farm_loc': 'பண்ணை இருப்பிடம்',
        'dash_pincode_placeholder': 'பின்கோடு உள்ளிடவும்',
        'dash_upload_photo': 'புகைப்படத்தைப் பதிவேற்றி AI வகைப்படுத்தவும்',
        'dash_click_upload': 'புகைப்படத்தைப் பதிவேற்ற கிளிக் செய்யவும்',
        'dash_ai_classify_btn': 'AI கழிவு வகைப்பாடு',
        'dash_map_title': 'கிராம தாக்க வரைபடம்',
        'dash_map_desc': 'எரியும் ஹாட்ஸ்பாட்களின் நிகழ்நேர செயற்கைக்கோள் கண்டறிதல்.',
        'dash_cert_btn': 'AI கார்பன் சான்றிதழைப் பதிவிறக்கவும்',
        'kyc_ocr_scanning': 'ஆவணத்தை ஸ்கேன் செய்கிறது...',
        'kyc_ocr_success': 'ஐடி வெற்றிகரமாக படிக்கப்பட்டது!',
        'dash_classifying': 'வகைப்படுத்தப்படுகிறது...',
        'dash_ai_complete': 'AI வகைப்பாடு முடிந்தது!',
        'dash_detected': 'கண்டறியப்பட்டது',
        'dash_confidence': 'நம்பிக்கை',
        'dash_price_prediction': 'AI விலை கணிப்பு',
        'dash_analyzing': 'சந்தையை ஆய்வு செய்கிறது...',
        'dash_estimated_value': 'AI பகுப்பாய்வின் அடிப்படையில் மதிப்பிடப்பட்ட சந்தை மதிப்பு.',
        // My Listings
        'list_title': 'எனது பட்டியல்கள்',
        'list_new_btn': '+ புதிய பட்டியல்',
        'list_on': 'பட்டியலிடப்பட்டது',
        'list_status_active': 'செயலில் உள்ளது',
        'list_status_sold': 'விற்கப்பட்டது',
        // AI Classify Page
        'ai_back_dash': 'டாஷ்போர்டிற்குத் திரும்பு',
        'ai_title': 'AI கழிவு வகைப்பாடு',
        'ai_desc': 'விவசாயக் கழிவுகளின் வகையைக் கண்டறியவும், மறுபயன்பாட்டு வாய்ப்புகளைக் கண்டறியவும் அதன் புகைப்படத்தைப் பதிவேற்றவும்',
        'ai_how_works': 'இது எப்படி வேலை செய்கிறது:',
        'ai_how_desc': 'எங்கள் AI மாடல் விவசாயக் கழிவுகளை அரிசி வைக்கோல், கோதுமை வைக்கோல், கரும்பு சக்கை மற்றும் பல போன்ற பிரிவுகளாக வகைப்படுத்த மேம்பட்ட பட அங்கீகாரத்தைப் பயன்படுத்துகிறது. சந்தை மதிப்பு மற்றும் தொழில்துறை மறுபயன்பாட்டு விருப்பங்கள் குறித்த உடனடி நுண்ணறிவுகளைப் பெறுவீர்கள்.',
        'ai_tips_title': 'சிறந்த முடிவுகளுக்கான குறிப்புகள்',
        'ai_tip_1_title': 'நல்ல வெளிச்சம்',
        'ai_tip_1_desc': 'பிரகாசமான, இயற்கையான வெளிச்சத்தில் புகைப்படங்களை எடுக்கவும்',
        'ai_tip_2_title': 'தெளிவான கவனம்',
        'ai_tip_2_desc': 'கழிவுகள் கவனத்தில் இருப்பதையும் தெளிவாகத் தெரிவதையும் உறுதி செய்யவும்',
        'ai_tip_3_title': 'நெருக்கமான ஷாட்',
        'ai_tip_3_desc': 'அமைப்பு மற்றும் விவரங்களைக் காட்ட நெருக்கமாக எடுக்கவும்',
        'ai_analyzing_img': 'படத்தை ஆய்வு செய்கிறது...',
        'ai_identifying': 'எங்கள் AI கழிவு வகையைக் கண்டறிகிறது',
        // KYC
        'kyc_title': 'உங்கள் KYC ஐ முடிக்கவும்',
        'kyc_desc': 'StubbleX இல் விற்கத் தொடங்க, உங்கள் அடையாளத்தைச் சரிபார்க்க வேண்டும். இது எங்கள் சமூகத்தைப் பாதுகாப்பாக வைக்க உதவுகிறது.',
        'kyc_requirement': 'சரிபார்ப்பிற்கு உங்கள் ஆதார் அட்டை அல்லது பான் கார்டு தேவைப்படும்.',
        'kyc_start_btn': 'சரிபார்ப்பைத் தொடங்கு',
        'kyc_verify_id': 'அடையாளத்தைச் சரிபார்க்கவும்',
        'kyc_upload_id_desc': 'உங்கள் அடையாளச் சான்றின் புகைப்படத்தைப் பதிவேற்றவும்',
        'kyc_doc_type': 'ஆவண வகை',
        'kyc_tap_capture': 'பிடிக்க அல்லது பதிவேற்ற தட்டவும்',
        'kyc_front_side': 'ஆவணத்தின் முன் பக்கம்',
        'kyc_id_number': 'அடையாள எண்',
        'kyc_enter_id': 'அடையாள எண்ணை உள்ளிடவும்',
        'kyc_submit_btn': 'சரிபார்ப்பிற்கு சமர்ப்பிக்கவும்',
        'kyc_verifying': 'சரிபார்க்கப்படுகிறது...',
        'kyc_success_title': 'சரிபார்ப்பு வெற்றி!',
        'kyc_success_desc': 'உங்கள் KYC முடிந்தது. இப்போது உலகளாவிய சந்தையில் உங்கள் தயாரிப்புகளைப் பட்டியலிடலாம்.',
        'kyc_go_dash': 'டாஷ்போர்டிற்குச் செல்லவும்',
        // Dashboard Nav
        'dash_nav_overview': 'கண்ணோட்டம்',
        'dash_nav_map': 'தாக்க வரைபடம்',
        'dash_nav_listings': 'எனது பட்டியல்கள்',
        'dash_nav_classify': 'AI கழிவு வகைப்பாடு',
        'dash_nav_leaderboard': 'தரவரிசைப் பட்டியல்',
        'dash_nav_profile': 'சுயவிவரம்',
        'dash_nav_orders': 'ஆர்டர்கள்',
        'dash_nav_company': 'நிறுவனத்தின் சுயவிவரம்',
        'dash_nav_settings': 'அமைப்புகள்',
        'dash_nav_signout': 'வெளியேறு',
        // How it Works Page
        'how_title': 'StubbleX எப்படி வேலை செய்கிறது',
        'how_farmer_step1': 'பட்டியலைப் பதிவேற்றவும்',
        'how_farmer_step1_desc': 'உங்கள் வைக்கோலைப் படம் பிடிக்கவும். எங்கள் AI தானாகவே வகையை (அரிசி/கோதுமை) கண்டறிந்து தரத்தை மதிப்பிடுகிறது.',
        'how_farmer_step2': 'உடனடி விலையைப் பெறுங்கள்',
        'how_farmer_step2_desc': 'தேவை, அளவு மற்றும் ஈரப்பதத்தின் அடிப்படையில் உலகளவில் கணக்கிடப்பட்ட நியாயமான சந்தை விலையைப் பெறுங்கள்.',
        'how_farmer_step3': 'பிக்கப்பைத் திட்டமிடுங்கள்',
        'how_farmer_step3_desc': 'விற்பனையை உறுதிப்படுத்துங்கள். கழிவுகளைச் சேகரிக்க ஒரு கூட்டாளர் தளவாட டிரக் உங்கள் பண்ணைக்கு வரும். உங்களுக்கு உடனடியாக பணம் கிடைக்கும்.',
        'how_buyer_step1': 'சந்தையை உலாவவும்',
        'how_buyer_step1_desc': 'வகை, இருப்பிடம், அளவு மற்றும் ஈரப்பதத்தின் அடிப்படையில் கிடைக்கும் உயிரினங்களை வடிகட்டவும். உண்மையான படங்களைப் பார்க்கவும்.',
        'how_buyer_step2': 'பாதுகாப்பான விநியோகம்',
        'how_buyer_step2_desc': 'மொத்தமாக ஆர்டர் செய்யுங்கள். சிறு பண்ணை நிலங்களை பெரிய, தொழில்துறைக்கு தயாரான ஏற்றுமதிகளாக நாங்கள் இணைக்கிறோம்.',
        'how_buyer_step3': 'தாக்கத்தைக் கண்காணிக்கவும்',
        'how_buyer_step3_desc': 'உங்கள் கார்பன் ஆஃப்செட் மற்றும் பாதுகாக்கப்பட்ட உயிரினங்களின் புள்ளிவிவரங்களை உங்கள் கார்ப்பரேட் டாஷ்போர்டிலிருந்து நேரடியாகக் கண்காணிக்கவும்.',
        // Dashboard
        'dash_title': 'விவசாயி டாஷ்போர்டு',
        'dash_earnings': 'மொத்த வருமானம்',
        'dash_waste_sold': 'விற்பனை செய்யப்பட்ட கழிவு',
        'dash_orders': 'நிறைவேற்றப்பட்ட ஆர்டர்கள்',
        'dash_new_listing': 'புதிய பட்டியல்',
        'list_now': 'விற்பனைக்கு பட்டியலிடுங்கள்',
        'use_voice': 'குரலைப் பயன்படுத்துங்கள்',
        'leaderboard': 'தரவரிசைப் பட்டியல்',
        'profile': 'சுயவிவரம்',
        'sign_out': 'வெளியேறு',
        'kyc_needed': 'KYC முடிக்கவும்'
    }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
    const [language, setLanguage] = useState<Language>('en');

    useEffect(() => {
        const savedLang = localStorage.getItem('appLanguage') as Language;
        if (savedLang && ['en', 'hi', 'ta'].includes(savedLang)) {
            setLanguage(savedLang);
        }
    }, []);

    const handleSetLanguage = (lang: Language) => {
        setLanguage(lang);
        localStorage.setItem('appLanguage', lang);
    };

    const t = (key: string) => {
        return translations[language][key] || translations['en'][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
}
